// <auto-generated />
using System;
using BookmakerWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookmakerWeb.Migrations
{
    [DbContext(typeof(BookmakerDbContext))]
    [Migration("20260426170118_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("BookmakerWeb.Models.Bet", b =>
                {
                    b.Property<int>("BetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BetDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Odds")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutCome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BetId");

                    b.HasIndex("MatchId");

                    b.HasIndex("UserId");

                    b.ToTable("Bets");

                    b.HasData(
                        new
                        {
                            BetId = 1,
                            Amount = 1000m,
                            BetDate = new DateTime(2024, 6, 14, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            MatchId = 1,
                            Odds = 2.10m,
                            OutCome = "Победа Реала",
                            UserId = 1
                        },
                        new
                        {
                            BetId = 2,
                            Amount = 500m,
                            BetDate = new DateTime(2024, 6, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchId = 2,
                            Odds = 1.85m,
                            OutCome = "Тотал больше 2.5",
                            UserId = 1
                        },
                        new
                        {
                            BetId = 3,
                            Amount = 2000m,
                            BetDate = new DateTime(2024, 6, 16, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchId = 3,
                            Odds = 1.75m,
                            OutCome = "Победа Lakers",
                            UserId = 2
                        },
                        new
                        {
                            BetId = 4,
                            Amount = 1500m,
                            BetDate = new DateTime(2024, 6, 15, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchId = 1,
                            Odds = 3.20m,
                            OutCome = "Ничья",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("BookmakerWeb.Models.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("MatchId");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            MatchId = 1,
                            EventName = "Реал Мадрид — Барселона",
                            Sport = "Футбол",
                            StartTime = new DateTime(2024, 6, 15, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MatchId = 2,
                            EventName = "ЦСКА — Спартак",
                            Sport = "Футбол",
                            StartTime = new DateTime(2024, 6, 16, 18, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MatchId = 3,
                            EventName = "Лейкерс — Голден Стэйт",
                            Sport = "Баскетбол",
                            StartTime = new DateTime(2024, 6, 17, 3, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BookmakerWeb.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegDate")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "ivanov@mail.ru",
                            FullName = "Иванов Иван Петрович",
                            PhoneNumber = "+79001234567",
                            RegDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 2,
                            Email = "petrova@mail.ru",
                            FullName = "Петрова Анна Сергеевна",
                            PhoneNumber = "+79007654321",
                            RegDate = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 3,
                            Email = "sidorov@mail.ru",
                            FullName = "Сидоров Алексей Михайлович",
                            PhoneNumber = "+79009876543",
                            RegDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BookmakerWeb.Models.Bet", b =>
                {
                    b.HasOne("BookmakerWeb.Models.Match", "Match")
                        .WithMany("Bets")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookmakerWeb.Models.User", "User")
                        .WithMany("Bets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookmakerWeb.Models.Match", b =>
                {
                    b.Navigation("Bets");
                });

            modelBuilder.Entity("BookmakerWeb.Models.User", b =>
                {
                    b.Navigation("Bets");
                });
#pragma warning restore 612, 618
        }
    }
}
